const lang = {
  en: {
    homePage: "Home Page",
    play: "Play",
    moreInfo: "More Info",
    popular: "Popular",
    upcoming: "Upcoming",
    topRated: "Top Rated",
    nowPlaying: "Now Playing",
    signOut: "Sign Out",
    GPTSearch: "GPT Search",
    search: "Search",
    GPTSearchPlaceholder: "What would you like to watch today?",
  },
  fr: {
    homePage: "Page d'accueil",
    play: "Lancer",
    moreInfo: "Plus d'informations",
    popular: "Populaire",
    upcoming: "À venir",
    topRated: "Les plus évalués",
    nowPlaying: "En ce moment",
    signOut: "Se déconnecter",
    GPTSearch: "Recherche GPT",
    search: "Recherche",
    GPTSearchPlaceholder: "Qu'est-ce que vous aimeriez regarder aujourd'hui ?",
  },
  es: {
    homePage: "Página principal",
    play: "Reproducir",
    moreInfo: "Más información",
    popular: "Popular",
    upcoming: "Próximos",
    topRated: "Más valorados",
    nowPlaying: "En este momento",
    signOut: "Cerrar sesión",
    GPTSearch: "Búsqueda GPT",
    search: "Buscar",
    GPTSearchPlaceholder: "¿Qué te gustaría ver hoy?",
  },
  hin: {
    homePage: "होम पेज",
    play: "खोले",
    moreInfo: "अधिक जानकारी",
    popular: "लोकप्रिय",
    upcoming: "आगामी",
    topRated: "सबसे ज्यादा रेटेड",
    nowPlaying: "अब देख रहे हैं",
    signOut: "बाहर करना",
    GPTSearch: "GPT खोजें",
    search: "खोजें",
    GPTSearchPlaceholder: "आज आप क्या देखना चाहते हैं?",
  },
};

export default lang;
